name: compass
channels:
  - mx
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.3.11=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=py311h06a4308_0
  - chardet=5.2.0=py311h38be061_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.1=py311h9547e67_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cycler=0.12.1=pyhd8ed1ab_0
  - datamol=0.12.4=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py311h459d7ec_0
  - freetype=2.12.1=h4a9f257_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fsspec=2024.5.0=pyhff2d567_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - greenlet=3.0.3=py311hb755f60_0
  - icu=73.2=h59595ed_0
  - idna=3.7=py311h06a4308_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py311h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.5=py311h9547e67_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.84.0=hba137d9_3
  - libboost-python=1.84.0=py311h5510f57_3
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.8=h7f8727e_5
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_7
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.80.2=hf974151_0
  - libgomp=13.2.0=h77fa898_7
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - loguru=0.7.2=py311h38be061_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib-base=3.8.4=py311ha4ca890_2
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h59595ed_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - openbabel=3.1.1=py311h8b422cb_9
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.0=hd590300_0
  - packaging=24.0=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pillow=10.3.0=py311h5eee18b_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.26.0=py311h8feb60e_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=hb806964_0_cpython
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - readline=8.2=h8228510_1
  - reduce=3.24=0
  - reportlab=4.1.0=py311h459d7ec_0
  - requests=2.31.0=py311h06a4308_1
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scikit-learn=1.4.2=py311he08f58d_1
  - scipy=1.13.0=py311h517d4fd_1
  - selfies=2.1.1=pyhd8ed1ab_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.30=py311h331c9d8_0
  - sympy=1.12=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.3.0=py311_cu121
  - torchtriton=2.3.0=py311
  - torchvision=0.18.0=py311_cu121
  - tqdm=4.66.4=pyhd8ed1ab_0
  - typing-extensions=4.11.0=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.1=py311h06a4308_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - art==6.2
      - attrs==23.2.0
      - bel-resources==0.0.3
      - biopandas==0.4.1
      - biopython==1.79
      - bioregistry==0.11.4
      - click==8.1.7
      - click-plugins==1.1.1
      - contextlib2==21.6.0
      - curies==0.7.9
      - deepspeed==0.5.9
      - dill==0.3.8
      - dllogger==1.0.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - e3nn==0.5.1
      - einops==0.8.0
      - fair-esm==2.0.0
      - fasteners==0.19
      - frozenlist==1.4.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gputil==1.4.0
      - griddataformats==1.0.2
      - hjson==3.1.0
      - huggingface-hub==0.23.1
      - humanize==4.9.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - lightning-utilities==0.11.2
      - matplotlib==3.9.0
      - mda-xdrlib==0.2.0
      - mdanalysis==2.7.0
      - ml-collections==0.1.1
      - mmtf-python==1.1.3
      - more-click==0.1.2
      - more-itertools==10.2.0
      - mrcfile==1.5.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - multisplitby==0.0.1
      - ninja==1.11.1.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - pandas==2.0.0
      - peft==0.11.1
      - prody==2.4.1
      - prolif==2.0.3
      - protobuf==4.25.3
      - psutil==5.9.8
      - psycopg2-binary==2.9.9
      - py-cpuinfo==9.0.0
      - py3dmol==2.1.0
      - pybel==0.15.5
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pyg-lib==0.4.0+pt23cu121
      - pystow==0.5.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.2.4
      - pytrie==0.4.0
      - ratelimit==2.2.1
      - rdkit==2023.9.6
      - rdkit-pypi==2022.9.5
      - referencing==0.35.1
      - regex==2024.5.15
      - requests-file==2.0.0
      - rpds-py==0.18.1
      - safetensors==0.4.3
      - seaborn==0.13.2
      - sentry-sdk==2.2.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - spyrmsd==0.7.0
      - tabulate==0.9.0
      - tokenizers==0.19.1
      - torch==2.3.0
      - torch-cluster==1.6.3+pt23cu121
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt23cu121
      - torch-sparse==0.6.18+pt23cu121
      - torch-spline-conv==1.2.2+pt23cu121
      - torchmetrics==1.4.0.post0
      - transformers==4.41.1
      - wandb==0.17.0
      - yarl==1.9.4
prefix: /home/asarigu/miniconda3/envs/compass
